export const Actions = {
  GET_CAPSULES: 'GET_CAPSULES',
  GET_LANDING_PAD: 'GET_LANDING_PAD',
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
}